#!/usr/bin/env bash
# Build a throwaway dev environment that is itself a git repo one commit behind
# its origin, so the nav update button can be driven by hand.
#
# `just dev` can't show that button: its dev-env root is this checkout — the
# repo you're working in, never behind, and not something a demo should
# fast-forward.
#
# Everything lands in .update-demo/ (gitignored). Re-run any time to reset.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
DEMO="$HERE/.update-demo"
ENVDIR="$DEMO/env"

rm -rf "$DEMO"
mkdir -p "$DEMO/checkouts"

# Fixed identity and no signing, so the demo commits don't depend on — or trip
# over — the developer's own gitconfig.
git_q() { git -c user.email=demo@example.com -c user.name=demo -c commit.gpgsign=false "$@"; }

# One service repo, so the branch/pull buttons and status table aren't empty.
git init -q --bare "$DEMO/app.git"
git -c init.defaultBranch=main init -q "$DEMO/app-seed"
git_q -C "$DEMO/app-seed" commit -q --allow-empty -m "init app"
git_q -C "$DEMO/app-seed" branch -q feature-x
git_q -C "$DEMO/app-seed" push -q "$DEMO/app.git" --all
rm -rf "$DEMO/app-seed"

git init -q --bare -b main "$DEMO/origin.git"
git -c init.defaultBranch=main init -q "$DEMO/seed"

# `workspace` keeps cloned service repos out of the dev-env checkout, so an
# untracked clone can never block its fast-forward.
cat > "$DEMO/seed/tilt-devenv.json" <<EOF
{
  "workspace": "$DEMO/checkouts",
  "repos": [
    {"name": "app", "url": "file://$DEMO/app.git", "group": "demo"}
  ]
}
EOF

echo 1 > "$DEMO/seed/VERSION"

# Generated, not checked in: it has to live inside the throwaway repo (that's
# what makes that repo a dev environment) and it bakes in absolute paths.
#
# Unquoted heredoc, so $vars interpolate — and backticks would run as commands.
cat > "$DEMO/seed/Tiltfile" <<EOF
# Generated by dev/update-demo.sh. Edits survive until the script is re-run.
allow_k8s_contexts(k8s_context())

load('$ROOT/tilt/Tiltfile', 'repos_load', 'repos_status_ui', 'repos_link')
load('ext://uibutton', 'cmd_button', 'location')

# Source builds, like dev/Tiltfile, so the rig exercises your working tree.
os.putenv('REPOS_BIN', 'cargo run --quiet --manifest-path $ROOT/Cargo.toml -p repos --')
# Polls fast, so an upstream change lands while you're still watching.
os.putenv('REPOS_TILTD_BIN',
          'cargo run --quiet --manifest-path $ROOT/Cargo.toml -p repos-tiltd -- --poll 10s')

repos = repos_load()
repos_status_ui(
    {name: name for name in repos},
    repos,
    labels=['repos'],
    deps=['$ROOT/crates'],
)

# Re-runs on restart, so the new version visibly lands after an update.
local_resource(
    'dev-env-version',
    cmd='echo "dev environment version \$(cat VERSION)"',
    labels=['dev-env'],
    allow_parallel=True,
)

# Stands in for a teammate pushing to the dev-env repo, so the update button can
# be re-armed without re-bootstrapping. Rig scaffolding only: the repos tool
# itself never pushes, and this "remote" is a bare repo under .update-demo/.
cmd_button(
    'simulate-upstream-update',
    argv=['bash', '$DEMO/simulate-upstream-update.sh'],
    location=location.NAV,
    icon_name='science',
    text='simulate an upstream update (test)',
)

for name in repos:
    local_resource(
        name,
        cmd='git -C %s branch --show-current' % repos[name].path,
        links=[repos_link(repos[name].url, 'Remote')],
        labels=['demo'],
        allow_parallel=True,
    )
EOF

git_q -C "$DEMO/seed" add -A
git_q -C "$DEMO/seed" commit -q -m "dev environment v1"
git_q -C "$DEMO/seed" push -q "$DEMO/origin.git" main

git clone -q "$DEMO/origin.git" "$ENVDIR"

cat > "$DEMO/simulate-upstream-update.sh" <<EOF
#!/usr/bin/env bash
# Plays the part of a teammate landing a change on the dev-env repo, so there's
# something for the update button to offer. Backs the nav "simulate an upstream
# update (test)" button; also runnable by hand.
set -euo pipefail
seed="$DEMO/seed"
next=\$(( \$(cat "\$seed/VERSION") + 1 ))
echo "\$next" > "\$seed/VERSION"
git -c user.email=demo@example.com -c user.name=demo -c commit.gpgsign=false \\
    -C "\$seed" commit -qam "dev environment v\$next"
git -C "\$seed" push -q "$DEMO/origin.git" main
echo "Upstream is now on v\$next. The update button appears within the 10s poll."
EOF
chmod +x "$DEMO/simulate-upstream-update.sh"

# Start one behind, so there's something to click the moment Tilt is up.
bash "$DEMO/simulate-upstream-update.sh" > /dev/null

echo "Wrote $ENVDIR — a dev environment 1 commit behind its origin."
echo
echo "Either mode shows a yellow update button in the Tilt nav, badged with how"
echo "many commits are pending. What a click does differs:"
echo
echo "  just update-demo        via 'repos up' — confirms, pulls, restarts Tilt."
echo "                          Watch dev-env-version go from v1 to v2."
echo
echo "  just update-demo-bare   via plain 'tilt up' — no supervisor, so it pulls"
echo "                          and says to restart yourself. dev-env-version"
echo "                          stays on v1 until you do."
echo
echo "Click 'simulate an upstream update (test)' to make it behind again."
